apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: usersapp
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: pgsql
  namespace: usersapp
spec:
  clusterIP: None
  selector:
    app: pgsql
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: usersapp
spec:
  clusterIP: None
  selector:
    app: node
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: usersapp
  namespace: usersapp
spec:
  secretName: usersapp
  dnsNames:
  - usersapp.vx
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: usersapp
  namespace: usersapp
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(\`usersapp.vx\`)
    services:
    - name: usersapp
      port: 3000
  tls:
    secretName: usersapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
  namespace: usersapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: docker.io/library/mysql:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_DATABASE
          value: users
        - name: MYSQL_USER
          value: node
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: db-mysql
          readOnly: true
      volumes:
      - name: db-mysql
        configMap:
          name: db-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
  labels:
    app: pgsql
  namespace: usersapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsql
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      containers:
      - name: pgsql
        image: docker.io/library/postgres:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_PASSWORD
          value: postgrespassword
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: db-pgsql
          readOnly: true
      volumes:
      - name: db-pgsql
        configMap:
          name: db-pgsql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  labels:
    app: node
  namespace: usersapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: docker.io/library/node:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        args:
        - npm install express express-session mysql2 pg path dotenv bcrypt hbs jsonwebtoken cookie-parser &&
          node app.js
        workingDir: /etc/usersapp
        env:
        - name: MY_HOST
          value: mysql.usersapp.svc.cluster.local
        - name: MY_DB
          value: users
        - name: MY_USER
          value: node
        - name: MY_PASSWORD
          value: password
        - name: PG_HOST
          value: pgsql.usersapp.svc.cluster.local
        - name: PG_DB
          value: users
        - name: PG_USER
          value: node
        - name: PG_PASSWORD
          value: password
        - name: JWT_PRIVATE_KEY
          value: /etc/usersapp/pki/jwt.key
        - name: JWT_PUBLIC_KEY
          value: /etc/usersapp/pki/jwt.pem
        volumeMounts:
        - mountPath: /etc/usersapp/pki
          name: node-pki
          readOnly: true
        - mountPath: /etc/usersapp/app.js
          subPath: app.js
          name: node-app
          readOnly: true
        - mountPath: /etc/usersapp/views
          name: node-views
          readOnly: true
      volumes:
      - name: node-app
        configMap:
          name: node-app
      - name: node-pki
        configMap:
          name: node-pki
      - name: node-views
        configMap:
          name: node-views