apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: usersapp
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/component: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: pgsql
  namespace: usersapp
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/component: pgsql
  ports:
  - name: pgsql
    port: 5432
    targetPort: 5432
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: usersapp
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/component: node
  ports:
  - name: node
    port: 3000
    targetPort: 3000
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: usersapp
  namespace: usersapp
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: usersapp.vx
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: node
            port:
              name: node
  tls:
  - hosts:
    - usersapp.vx
    secretName: usersapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: usersapp
    app.kubernetes.io/component: mysql
  namespace: usersapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: usersapp
        app.kubernetes.io/component: mysql
    spec:
      containers:
      - name: mysql
        image: docker.io/library/mysql:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_DATABASE
          value: users
        - name: MYSQL_USER
          value: node
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: db-mysql
          readOnly: true
      volumes:
      - name: db-mysql
        configMap:
          name: db-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
  namespace: usersapp
  labels:
    app.kubernetes.io/name: usersapp
    app.kubernetes.io/component: pgsql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: pgsql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: usersapp
        app.kubernetes.io/component: pgsql
    spec:
      containers:
      - name: pgsql
        image: docker.io/library/postgres:alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_PASSWORD
          value: postgrespassword
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: db-pgsql
          readOnly: true
      volumes:
      - name: db-pgsql
        configMap:
          name: db-pgsql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  namespace: usersapp
  labels:
    app.kubernetes.io/name: usersapp
    app.kubernetes.io/component: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: usersapp
      app.kubernetes.io/component: node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: usersapp
        app.kubernetes.io/component: node
    spec:
      containers:
      - name: node
        image: docker.io/library/node:alpine
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
        - npm install express express-session mysql2 pg path dotenv bcrypt hbs jsonwebtoken cookie-parser &&
          node app.js
        workingDir: /etc/usersapp
        env:
        - name: MY_HOST
          value: mysql.usersapp.svc.cluster.local
        - name: MY_DB
          value: users
        - name: MY_USER
          value: node
        - name: MY_PASSWORD
          value: password
        - name: PG_HOST
          value: pgsql.usersapp.svc.cluster.local
        - name: PG_DB
          value: users
        - name: PG_USER
          value: node
        - name: PG_PASSWORD
          value: password
        - name: JWT_PRIVATE_KEY
          value: /etc/usersapp/pki/jwt.key
        - name: JWT_PUBLIC_KEY
          value: /etc/usersapp/pki/jwt.pem
        volumeMounts:
        - mountPath: /etc/usersapp/pki
          name: node-pki
          readOnly: true
        - mountPath: /etc/usersapp/app.js
          subPath: app.js
          name: node-app
          readOnly: true
        - mountPath: /etc/usersapp/views
          name: node-views
          readOnly: true
      volumes:
      - name: node-app
        configMap:
          name: node-app
      - name: node-pki
        configMap:
          name: node-pki
      - name: node-views
        configMap:
          name: node-views